name: flutter_tizen
description: Flutter application build tools for Tizen devices
homepage: https://github.com/flutter-tizen/flutter-tizen
version: 2.5.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  archive:
  flutter_tools:
    path: flutter/packages/flutter_tools
  file:
  meta:
  package_config:
  path:
  process:
  xml:
  yaml:

dev_dependencies:
  args:
  file_testing:
  flutter_test:
    sdk: flutter
  pubspec_parse:
  test:
