name: flutter_tizen
description: Flutter application build tools for Tizen devices
homepage: https://github.com/flutter-tizen/flutter-tizen
version: 1.22.12-pre.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_tools:
    path: flutter/packages/flutter_tools
  file: any
  meta: any
  package_config: any
  path: any
  process: any
  xml: any
  yaml: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  pedantic: any
  test: any
