name: flutter_tizen
description: Tizen utilities for Dart and Flutter.
version: 0.2.5
homepage: https://github.com/flutter-tizen/flutter-tizen/tree/master/packages/flutter_tizen

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
